services:
  - type: web
    name: booking-live
    env: python
    buildCommand: |
      pip install --upgrade pip
      pip install -r requirements.txt
    startCommand: gunicorn app:app
    plan: free
    autoDeploy: true
    pythonVersion: "3.11"
